version: 1
project_name: byoh-agent

builds:
  # from make host-agent-binaries
  - id: byoh-agent
    main: ./agent 
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -w -s
      - -extldflags '-static'
      - -X 'github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/agent/version.GitMajor={{ .Major }}'
      - -X 'github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/agent/version.GitMinor={{ .Minor }}'
      - -X 'github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/agent/version.GitVersion={{ .Version }}'
      - -X 'github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/agent/version.GitCommit={{ .Commit }}'
      - -X 'github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/agent/version.GitTreeState={{ .GitTreeState }}'
      - -X 'github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/agent/version.BuildDate={{ .Date }}'

nfpms:
  - file_name_template: "{{ .PackageName }}_{{ .RawVersion }}~{{ .Prerelease }}_{{ .Arch }}"
    maintainer: vmware
    description: BYOH agent
    homepage: https://github.com/nebius/cluster-api-provider-bringyourownhost
    license: Apache 2.0
    formats:
      - deb
    contents:
      - src: debian/systemd
        dst: /etc/systemd/system/
        type: tree

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release: 
  disable: true  # don't push artifacts to GH

uploads:
  - name: upload
    method: POST
    target: "{{ .Env.UPLOAD_URL }}"
    custom_artifact_name: true
    exts:
      - deb
    custom_headers:
      Authorization: "Bearer {{ .Env.UPLOAD_TOKEN }}"
