# ClusterRole 
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRole 
metadata: 
  name: csr-creator-clusterrole 
rules: 
- apiGroups: 
  - certificates.k8s.io 
  resources: 
  - certificatesigningrequests 
  verbs: 
  - create 
  - get 
  - watch 
—-- 
# ClusterRoleBinding 
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRoleBinding 
metadata: 
  name: csr-creator-clusterrole-binding 
roleRef: 
  apiGroup: rbac.authorization.k8s.io 
  kind: ClusterRole 
  name: csr-creator-clusterrole 
subjects: 
- apiGroup: rbac.authorization.k8s.io 
  kind: Group 
  name: system:bootstrappers:byoh 