// Code generated by counterfeiter. DO NOT EDIT.
package cloudinitfakes

import (
	"io/fs"
	"sync"

	"github.com/vmware-tanzu/cluster-api-provider-byoh/agent/cloudinit"
)

type FakeFileWriter struct {
	MkdirStub        func(string, fs.FileMode)
	mkdirMutex       sync.RWMutex
	mkdirArgsForCall []struct {
		arg1 string
		arg2 fs.FileMode
	}
	WriteToFileStub        func(string, string)
	writeToFileMutex       sync.RWMutex
	writeToFileArgsForCall []struct {
		arg1 string
		arg2 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFileWriter) Mkdir(arg1 string, arg2 fs.FileMode) {
	fake.mkdirMutex.Lock()
	fake.mkdirArgsForCall = append(fake.mkdirArgsForCall, struct {
		arg1 string
		arg2 fs.FileMode
	}{arg1, arg2})
	stub := fake.MkdirStub
	fake.recordInvocation("Mkdir", []interface{}{arg1, arg2})
	fake.mkdirMutex.Unlock()
	if stub != nil {
		fake.MkdirStub(arg1, arg2)
	}
}

func (fake *FakeFileWriter) MkdirCallCount() int {
	fake.mkdirMutex.RLock()
	defer fake.mkdirMutex.RUnlock()
	return len(fake.mkdirArgsForCall)
}

func (fake *FakeFileWriter) MkdirCalls(stub func(string, fs.FileMode)) {
	fake.mkdirMutex.Lock()
	defer fake.mkdirMutex.Unlock()
	fake.MkdirStub = stub
}

func (fake *FakeFileWriter) MkdirArgsForCall(i int) (string, fs.FileMode) {
	fake.mkdirMutex.RLock()
	defer fake.mkdirMutex.RUnlock()
	argsForCall := fake.mkdirArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeFileWriter) WriteToFile(arg1 string, arg2 string) {
	fake.writeToFileMutex.Lock()
	fake.writeToFileArgsForCall = append(fake.writeToFileArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.WriteToFileStub
	fake.recordInvocation("WriteToFile", []interface{}{arg1, arg2})
	fake.writeToFileMutex.Unlock()
	if stub != nil {
		fake.WriteToFileStub(arg1, arg2)
	}
}

func (fake *FakeFileWriter) WriteToFileCallCount() int {
	fake.writeToFileMutex.RLock()
	defer fake.writeToFileMutex.RUnlock()
	return len(fake.writeToFileArgsForCall)
}

func (fake *FakeFileWriter) WriteToFileCalls(stub func(string, string)) {
	fake.writeToFileMutex.Lock()
	defer fake.writeToFileMutex.Unlock()
	fake.WriteToFileStub = stub
}

func (fake *FakeFileWriter) WriteToFileArgsForCall(i int) (string, string) {
	fake.writeToFileMutex.RLock()
	defer fake.writeToFileMutex.RUnlock()
	argsForCall := fake.writeToFileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeFileWriter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mkdirMutex.RLock()
	defer fake.mkdirMutex.RUnlock()
	fake.writeToFileMutex.RLock()
	defer fake.writeToFileMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFileWriter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cloudinit.FileWriter = new(FakeFileWriter)
