@startuml Del-byomachine
title
Current - Remove ByoMachine
end title

actor "platform operator" as po
participant HostAgent as hagent <<(A,#ADD1B2)>>
box "Management Cluster" #LightBlue
    participant APIServer as mc <<(S,#ADD1B2) >>
    participant ByoMachineController as bmc <<(C,#ADD1B2)>>
end box

box "Workload Cluster" #LightPink
    participant APIServer as wc <<(S,#ADD1B2) >>
end box 


po->mc: Deletes/Down Scale a ByohCluster
note right of mc
Delete Op for 
1. Owner CapiMachine
2. ByoMachine
end note

mc --> bmc: Receive Reconcile Event
note right of bmc
    1. Preconditions checks
      a. ByoMachine/CapiMachine/CapiCluster
      b. Paused Annotation
    2. ReconcileDelete
end note
bmc -> mc: Patch Attached <b>ByoHost</b> Add \n 1. Annotations[hostCleanupAnnotation]
mc --> hagent: Receive Reconcile Event
note left of hagent
    1. Preconditions Checks
      a. Paused Annotation
    2. hostCleanUp
      a. Kubeadm reset
end note
hagent -> mc: Patch <b>ByoHost</b> \n 1.K8sNodeBootstrapSucceeded \n   with K8sNodeAbsentReason
mc --> bmc: Enqueue Reconcile event for ByoHost
note right of bmc
    1. Preconditions checks
      a. ByoMachine/CapiMachine/CapiCluster
      b. Paused Annotation
    2. ReconcileDelete
end note
bmc -> mc: Patch Attached <b>ByoHost</b> Remove \n 1. Status.MachineRef \n 2. ByoHost.Labels \n 3. Annotations
bmc -> mc: Patch <b>ByoMachine</b> Remove \n 1. Finalizer

@enduml
