name: Check Markdown links

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        base-branch: 'main'
        config-file: '.github/workflows/markdown.links.config.json'
